Repository xiegeo/commit-sudoku, pull requests merged in 2018-07, with the labels that each got.

#46 Add a 3 at r1, c8
  README.md
Labels: move

#48 Update README.md
  README.md
Labels: move

#49 Add 6 to R1,C6
  README.md
Labels: move

#52 Add 2 to r2,c3
  README.md
Labels: move

#53 add 7 at r3c6
  README.md
Labels: move

#56 block animation on PRs too
  .travis.yml
Labels: code

#55 put 2 at r8c1
  README.md
Labels: move

#57 9 at r2,c2
  README.md
Labels: move

#58 6 should have been a 2
  README.md
Labels: move

#59 complete the square
  README.md
Labels: move

#62 Seven 7s
  README.md
Labels: move

#63 fix(animation): Exclude merges from animation
  animation/index.js
Labels: code

#61 add 2 at r8 c1
  README.md
Labels: move

#68 3 at r6 c1
  README.md
Labels: move

#70 9 in [r8,c3]
  README.md
Labels: move

#75 fix(animation): Animate entire git history
  .travis.yml
Labels: bug

#77 chore(ci): Cache npm dependencies
  .travis.yml
Labels: code

#78 an 8 on the 8th row
  README.md
Labels: move
